version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50505:50505"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    volumes:
      - .:/code
